export const LOADING = "LOADING";
export const LOADED = "LOADED";
export const ERROR = "ERROR";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_AUTH_REDIRECT = "SET_AUTH_REDIRECT";
export const CLEAR_AUTH_REDIRECT = "CLEAR_AUTH_REDIRECT";
export const GDPR_AGREED = "GDPR_AGREED";
export const TOS_AGREED = "TOS_AGREED";
export const RD_AGREED = "RD_AGREED";

export const ADD_TOASTER = "ADD_TOASTER";
export const REMOVE_TOASTER = "REMOVE_TOASTER";
export const CLEAR_ALL = "CLEAR_ALL"

export const SHOW_DIALOG = "SHOW_DIALOG";
export const SILENCE_DIALOG = "SILENCE_DIALOG";
export const LOADING_DIALOG = "LOADING_DIALOG";

export const ADD_BET = "ADD_BET";
export const MOVE_TO_NEXT_DAY = "MOVE_TO_NEXT_DAY";
export const ADD_LAST_3_DAYS_PROFIT = "ADD LAST 3 DAYS PROFIT";
export const RESET_BOARD = "RESET_BOARD";
export const TOGGLE_BOARD_MODE = "TOGGLE_BOARD_MODE";
export const UPDATE_DATE = "UPDATE_DATE";
export const UPDATE_BET = "UPDATE_BET";
export const INITIALIZE_DATA = "INITIALIZE_DATA";

export const FINISH_LOADING = "FINISH_LOADING";
export const START_LOADING = "START_LOADING";
export const SHOW_HEATMAP = "SHOW_HEATMAP";
export const INITIALIZE_HEATMAP = "INITIALIZE_HEATMAP";
export const SHOW_PERFORMANCE = "SHOW_PERFORMANCE"
export const SHOW_LOCKDOWN_DIALOG = "SHOW_LOCKDOWN_DIALOG"
export const SHOW_LEADER_DIALOG = "SHOW_LEADER_DIALOG"
export const SET_MUTE="SET_MUTE";