// flow-typed signature: 0b6ccea4d4dcf44794b2510f5af3b01d
// flow-typed version: <<STUB>>/docdash_v^0.4.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docdash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'docdash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docdash/fixtures/base/chains' {
  declare module.exports: any;
}

declare module 'docdash/fixtures/base/index' {
  declare module.exports: any;
}

declare module 'docdash/fixtures/documents/binder' {
  declare module.exports: any;
}

declare module 'docdash/fixtures/documents/collector' {
  declare module.exports: any;
}

declare module 'docdash/fixtures/documents/model' {
  declare module.exports: any;
}

declare module 'docdash/fixtures/documents/probe' {
  declare module.exports: any;
}

declare module 'docdash/fixtures/documents/schema' {
  declare module.exports: any;
}

declare module 'docdash/fixtures/mixins/bussable' {
  declare module.exports: any;
}

declare module 'docdash/fixtures/mixins/signalable' {
  declare module.exports: any;
}

declare module 'docdash/fixtures/strings/format' {
  declare module.exports: any;
}

declare module 'docdash/fixtures/utils/logger' {
  declare module.exports: any;
}

declare module 'docdash/publish' {
  declare module.exports: any;
}

declare module 'docdash/static/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'docdash/static/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'docdash/static/scripts/prettify/prettify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docdash/fixtures/base/chains.js' {
  declare module.exports: $Exports<'docdash/fixtures/base/chains'>;
}
declare module 'docdash/fixtures/base/index.js' {
  declare module.exports: $Exports<'docdash/fixtures/base/index'>;
}
declare module 'docdash/fixtures/documents/binder.js' {
  declare module.exports: $Exports<'docdash/fixtures/documents/binder'>;
}
declare module 'docdash/fixtures/documents/collector.js' {
  declare module.exports: $Exports<'docdash/fixtures/documents/collector'>;
}
declare module 'docdash/fixtures/documents/model.js' {
  declare module.exports: $Exports<'docdash/fixtures/documents/model'>;
}
declare module 'docdash/fixtures/documents/probe.js' {
  declare module.exports: $Exports<'docdash/fixtures/documents/probe'>;
}
declare module 'docdash/fixtures/documents/schema.js' {
  declare module.exports: $Exports<'docdash/fixtures/documents/schema'>;
}
declare module 'docdash/fixtures/mixins/bussable.js' {
  declare module.exports: $Exports<'docdash/fixtures/mixins/bussable'>;
}
declare module 'docdash/fixtures/mixins/signalable.js' {
  declare module.exports: $Exports<'docdash/fixtures/mixins/signalable'>;
}
declare module 'docdash/fixtures/strings/format.js' {
  declare module.exports: $Exports<'docdash/fixtures/strings/format'>;
}
declare module 'docdash/fixtures/utils/logger.js' {
  declare module.exports: $Exports<'docdash/fixtures/utils/logger'>;
}
declare module 'docdash/publish.js' {
  declare module.exports: $Exports<'docdash/publish'>;
}
declare module 'docdash/static/scripts/linenumber.js' {
  declare module.exports: $Exports<'docdash/static/scripts/linenumber'>;
}
declare module 'docdash/static/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'docdash/static/scripts/prettify/lang-css'>;
}
declare module 'docdash/static/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'docdash/static/scripts/prettify/prettify'>;
}
